server {
    listen 3200;
    server_name localhost;

    root /var/www/templeossy/dist;
    index index.html;

    add_header Cross-Origin-Opener-Policy same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;
    add_header Cross-Origin-Resource-Policy same-origin always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.wasm$ {
        default_type application/wasm;
        try_files $uri =404;
    }

    location ~* \.data$ {
        default_type application/octet-stream;
        try_files $uri =404;
    }
}
